### ISSUE TITLE
Create documentation for advanced js

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1431] opened 2023-12-06 22:00 UTC
## Create documentation for advanced js

In a nutshell, we need to create easily followable steps to how to set up sites to use mega menus and mobile menus.
See https://github.com/NCIOCPL/ncids/wiki/Technical-NCI-Header-Design

### Tasks

- [ ] Header mega menu source
- [ ] Header mobile menu source

**Comment by olitharp-nci** [comment] 2023-12-07 15:36
wip content

# Advanced JS

## Mega menu source

A mega menu source is currently required for the Header with mega menu component. To customize the mega menu, you must...

## Mobile menu source 

A mobile menu source is not required for a mobile menu. The default source is used with auto initialization. However, to customize the mobile menu you must...

**Comment by bennettcc** [comment] 2024-01-03 16:01
Closing as a dupe of https://github.com/NCIOCPL/ncids/issues/1432

**Closed by bennettcc** 2024-01-03 16:01 UTC
Labels: Needs Technical Review, DS Development
