### ISSUE TITLE
Image & Video Caption - Add padding right

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#1893] opened 2024-11-01 18:20 UTC
### Issue description
The padding-right on captions are missing. Screenshot below
> **ESTIMATE** TBD

### What's the expected result?
- Padding-right 16px (token 2)

### What's the actual result?
- no padding right

### Additional details / screenshot
![Image](https://github.com/user-attachments/assets/aadc1c8d-19de-413f-b18c-1104f7ba50bb)
![Image](https://github.com/user-attachments/assets/b424583f-9d15-46ce-9406-54fe4e1a22b2)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment] 2024-11-04 15:42
Closing this ticket since the issue is on Digital Platform not NCIDS.

**Closed by andyvanavery31** 2024-11-04 15:42 UTC
Labels: Bug
