### ISSUE TITLE
Display NCI Banner flag icon on example site

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#700] opened 2023-01-09 23:51 UTC
## Issue description
The [example site](https://designsystem-dev.cancer.gov/develop/example-site/) currently does not display the flag icon in the NCI Banner component. 

> **ESTIMATE** TBD

### What's the expected change?
- The NCI Banner component displays the flag icon on the example site.

### What's the current functionality?
- The NCI Banner component does not display the flag icon on the example site.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
<img width="733" alt="Screenshot 2023-08-30 at 11 23 28 AM" src="https://github.com/NCIOCPL/ncids/assets/24591940/d90ce690-b798-44ca-ac60-7f19e69352dd">

**Comment by bennettcc** [comment] 2024-10-07 18:04
Closing this ticket - not able to reproduce issue. Confirmed in 10/7 conversation with Paul + Joe

**Closed by bennettcc** 2024-10-07 18:04 UTC
Labels: Change Request
