### ISSUE TITLE
Update anchor link display for headings

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1309] opened 2023-10-12 01:43 UTC
### Issue description
Currently, when you hover on any heading, the (rather large) link icon will display to the left of the heading. When you click, it takes you to that particular section and appends the anchor to the URL. To share the link to that section, you have to manually copy that URL.

We'd like to update this to always display a smaller icon that is grey (but still accessible) to the right of the header. Upon clicking, this link would copy the link to that section.

Example of what we want it to look like: https://polaris.shopify.com/components/actions/account-connection#for-example

### What's the expected change?
- A heading anchor link displays a smaller icon that is grey (but still accessible) to the right of the header. On click, the link to that section is copied.

### What's the current functionality?
- A heading anchor link is a large link icon displaying to the left of the heading on hover. On click, it takes you to the section with the anchor in the URL, and you have to manually copy.

### What's the updated acceptance criteria?
```gherkin
Scenario: A user views the NCIDS Documentation Site and copies a link to a specific heading on one of the pages
  Given The Copy Link icon has been updated to match the new comp
  When a user visits the NCIDS Documentation Site
    And they go to an h2 or h3 heading
  Then the user will see the updated Copy Link icon
    And the icon will be on the right side of the heading
    And the icon will always be visible
    And the icon will meet accessibility requirements
  When the user clicks on the Copy Link icon to the right of the heading
  Then the link to that heading section will be copied to the users clipboard
```

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by laurelthrash** [comment] 2023-10-12 17:54
@sarinapadilla @andyvanavery31 Recommend confirming our proposed requirements with the federal team before we start building. Consider creating a comp/prototype (if the LOE to do so does not outweigh the benefits) to demonstrate our idea.

**Comment by laurelthrash** [comment] 2024-01-30 19:19
@dcvijanovic1k @blilianyu - Next step is to update the comps to show this approved anchor link display change. We'll need to determine the best way to show the hover and click state interactions in Figma.

**Comment by blilianyu** [comment] 2024-01-31 16:39
@laurelthrash here is the prototype for review. cc: @dcvijanovic1k 

https://www.figma.com/proto/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?page-id=1180%3A9396&type=design&node-id=1180-9397&viewport=-226%2C907%2C0.5&t=BrN0a63lXxit3PuE-1&scaling=min-zoom&starting-point-node-id=1180%3A9397&mode=design

**Comment by laurelthrash** [comment] 2024-02-01 19:25
Prototype updated based on Requirements meeting 01/31. Approved by design side via Slack. Will share with Anna during end of sprint 02/06 and obtain approval before sending to dev side.

**Comment by laurelthrash** [comment] 2024-02-08 14:12
Shared design with Anna during end of sprint on 02/06/24 and received sign off. Passing to the development side for implementation. Marking as "done" on design board. Cc: @andyvanavery31 @sarinapadilla @bennettcc  @blilianyu @dcvijanovic1k

**Closed** 2024-02-28 17:23 UTC
Labels: Needs Technical Review, Change Request, DS Development
