### ISSUE TITLE
Typography links in the main content throw a 404 error when clicked

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/ncids#1660] opened 2024-04-18 14:26 UTC
### Issue description
In the doc site - the Typography links in the main content throw a 404 error when clicked

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  go to https://designsystem-dev.cancer.gov/develop/foundations/typography/
2. scroll to the bottom of the page
3. click one of the 3 links

### What's the expected result?
- you get to the actual content

### What's the actual result?
- 404 error

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bennettcc** [comment] 2024-04-18 14:59
Not able to reproduce this issue - closing ticket. Links seems to work as expected

**Closed by bennettcc** 2024-04-18 14:59 UTC
