### ISSUE TITLE
Story: Add Error State Modifier for Dark Backgrounds for Form Inputs

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1478] opened 2024-01-11 17:18 UTC
### New Feature Request
This request is to add a modifier to the Error State for File Inputs so that it meets accessibility requirements when displayed on dark backgrounds.

Classes that have `error-dark`:
**Components**
* `.usa-input--error`
* `.usa-form-group--error`
* `.usa-input-group--error`
   * Located in `usa-input-prefix-suffix`
* `* .usa-form-group--error .usa-file-input__target` 
    * we manually patched to `error-dark`
*  `.has-invalid-file .usa-file-input__accepted-files-message` 
     * we manually patched to `error-dark`
*  `.usa-character-count__status.usa-character-count__status--invalid`
    * Wins for stupidest class name
* `.usa-label--required`
   * Which is kind of confusing because `usa-label--error` is only bolding the text. 
* `.usa-error-message`
* .has-invalid-file .usa-file-input__accepted-files-message
   * this is actually in our patch.

### What's the expected change?
- A modifier will be made to the Error State so that it will meet accessibility requirements on dark backgrounds.
- All error states need to change from `error-dark` to `error`
- Use the [comp for the Error State Modifier](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=6374-11972&mode=design)

   
### What's the current functionality?
- There is no modifier of the error state for use on dark backgrounds.
- Error states use `error-dark`

**Comment by blilianyu** [comment] 2024-01-18 20:32
Here is the [Error State Modifier](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=3993%3A10961&mode=design&t=udH64WztmlBKgqeg-1) and the modifier applied to [combo box](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=5869%3A11262&mode=design&t=udH64WztmlBKgqeg-1) for review.
_Note: I have not moved this into ‘NCIDS Components’ page yet (it will be a new page `Text Input`)._

In addition to this the following changes have also been made:
- [text-inputs](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=3993%3A10961&mode=design&t=udH64WztmlBKgqeg-1) and [form templates](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=6011%3A11846&mode=design&t=udH64WztmlBKgqeg-1) have been split to its own pages from [form controls](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=6011%3A12792&mode=design&t=udH64WztmlBKgqeg-1)
- `text-area` has been removed from `text-input` as it is a dupe of [character count](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=3993%3A11001&mode=design&t=udH64WztmlBKgqeg-1)

cc: @dcvijanovic1k @laurelthrash

**Comment by laurelthrash** [comment] 2024-01-25 15:32
Complete from design side. Closing on design board for time being.

**Comment by bryanpizzillo** [comment] 2024-01-26 18:20
## Investigation Notes

**Weirdo**The file upload when in an error has a different color for the dotted outline. However, it is red in our storybook, and secondary-dark is not red. so 🤷‍♂️ 
```
// Error states
.usa-form-group--error .usa-file-input__target {
  border-color: color("secondary-dark");
  border-width: 2px;
}
```

**Comment by bryanpizzillo** [comment] 2024-02-01 20:14
### Scenarios
* Storybook
   * Add a folder under components called `forms` which looks like:
      * 📂 Forms
         * 📄 Form Elements
            * No Errors
               * Scenario 1. Form Group in Light background (no error)
                  * usa-form-group
                     * usa-label
                     * usa-hint
               * Scenario 2. Form Group in Dark background (no error)
                  * usa-section.usa-section-dark
                     * usa-form-group
                        * usa-label
                        * usa-hint
               * Scenario 3. Fieldset light background
                  * usa-fieldset
                     * usa-legend
                     * usa-label
                     * usa-hint
               * Scenario 4. Fieldset dark background
                  * usa-section.usa-section-dark
                     * usa-fieldset
                        * usa-legend
                        * usa-label
                        * usa-hint
            * Errors
               * Scenario 1. Light background (no error)
                  * usa-form-group.usa-form-group--error
                     * usa-label.usa-label--error
                     * usa-hint
                     * usa-error-message
               * Scenario 2. Dark background (no error)
                  * usa-section.usa-section-dark
                     * usa-form-group.usa-form-group--error
                        * usa-label.usa-label--error
                        * usa-hint
                        * usa-error-message
            * 
            * usa-form-group
            * usa-hint
         * 📂 Form Controls
            * ...

**Closed** 2024-02-14 15:25 UTC
Labels: Needs Product Review, Patch
