### ISSUE TITLE
Prose USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#867] opened 2023-03-30 16:45 UTC
### USWDS Component Name
[Prose](https://designsystem.digital.gov/components/prose/)

### USWDS Component Packages
* Package usage: `@forward "usa-prose";`
* Dependencies: `uswds-fonts`

### Subtasks
- [ ] Make a folder with the component name under uswds-native
- [ ] Copy USWDS twig and any JSON
- [ ] Make an index.scss for the stories
- [ ] Copy and hack up USWDS stories.js file to use our story format
- [ ] Create scenarios.js by adding a scenario for each story in stories.js
- [ ] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by sarinapadilla** [comment] 2023-04-06 16:03
Oops, created a dupe of this one. I've added the notes from our meeting to the other one so I'll close this one!

**Closed by sarinapadilla** 2023-04-06 16:03 UTC
Labels: uswds-native
